### ISSUE TITLE
Better repository/project name

### ISSUE THREAD

**Issue by dginev** [KWARC/LATEXML_FEED#1]
1. Please don't use all-caps
  2. I am unsure what the project is about, but is it possible to avoid using LaTeXML's name unless this is directly related to the latexml ecosystem? (e.g. it is a plugin/fork, etc.)

If you're normalizing math on the web, you can do something creative like "normath" etc.

**Comment by kohlhase** [comment]
I fully agree.

**Comment by m-iancu** [comment]
I moved this to https://github.com/KWARC/MWS_Harvesters, Will delete this repo soon.
